#!/bin/env perl
use v5.38.0;

use lib 'lib';

use IO::Async::Loop;
use IO::Socket;
use Time::HiRes ();

use Nib::Config;
use Nib::Dev;

my $config = Nib::Config->read_file('nib.toml');

my $dev = Nib::Dev->new(config => $config);
my $loop = IO::Async::Loop->new;
$loop->add($dev);

$dev->set_streaming->get;

my @panel_ids = (22456, 9927, 8746, 6265, 19564, 9033);

$dev->set_panel($_, 0, 0, 0, 0) for @panel_ids;

$SIG{INT} = sub {
  $dev->set_panel($_, 0, 0, 0, 0) for @panel_ids;
  die "Interrupted!\n";
};

my @colors = (
  [ 0xA0, 0x00, 0x00 ],
  [ 0x00, 0xA0, 0x00 ],
  [ 0x00, 0x00, 0xA0 ],
);

my $color = 0;

while (1) {
  for my $i (0 .. $#panel_ids) {
    $dev->set_panel($panel_ids[$i], $colors[$color]->@*, 0);
    Time::HiRes::sleep(0.15);
    $dev->set_panel($panel_ids[($i+1) % @panel_ids], 0, 0, 0, 0);
  }

  $color = ($color + 1) % @colors;
}
