#!/bin/env perl
use v5.38.0;
use utf8;

binmode *STDOUT, ':encoding(UTF-8)';

use Getopt::Long::Descriptive;
use IO::Socket;

use lib 'lib';
use Nib::TouchUtil;

my ($opt, $usage) = describe_options(
  '%c %o',
  [ 'port|p=i', 'port to listen on', { default => '9991' } ],
);

my $sock = IO::Socket::INET->new(
  LocalPort => $opt->port,
  Proto     => 'udp'
) or die "socket fail: $@";

say "Now listening on 0.0.0.0:" . $opt->port;

my $counter = 1;

while ($sock->recv(my $newmsg, 1024)) {
  Nib::TouchUtil->dump_dgram($newmsg, $counter++);
}

